# Generated by Django 6.0.5 on 2026-06-04 07:23

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_favoriteauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
