# Generated by Django 5.1.7 on 2025-03-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_story_comment_story_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='story_id',
            new_name='story',
        ),
    ]
