# Generated by Django 5.1.7 on 2025-03-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_rename_story_id_comment_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='story',
            new_name='story_id',
        ),
    ]
