# Generated by Django 6.0.5 on 2026-06-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_alter_comment_options_comment_updated_at_commentlike_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
