# Generated by Django 5.1.7 on 2025-03-11 08:26

from django.db import migrations, models
import random

def add_stories(apps, schema_editor):
    Story = apps.get_model('stories', 'Story')
    Category = apps.get_model('categories', 'Category')

    categories = list(Category.objects.all())  # Fetch all categories

    stories_data = [
        {"title": "The Enchanted Forest", "author": "Alice"},
        {"title": "Space Odyssey", "author": "Bob"},
        {"title": "The Secret Code", "author": "Charlie"},
        {"title": "Love in Paris", "author": "Diana"},
        {"title": "Haunted Mansion", "author": "Ethan"},
        {"title": "The Lost Kingdom", "author": "Fiona"},
        {"title": "Journey to the Unknown", "author": "George"},
        {"title": "The Diary of a Scientist", "author": "Hannah"},
        {"title": "My Life Memoir", "author": "Ian"},
        {"title": "Success and You", "author": "Julia"}
    ]

    for story_data in stories_data:
        story = Story.objects.create(**story_data)
        story_categories = random.sample(categories, random.randint(1, 3))  # Assign 1 to 3 categories
        story.categories.set(story_categories)

class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='stories', to='categories.category'),
        ),
        migrations.RunPython(add_stories)
    ]
