# Generated by Django 5.1.7 on 2025-03-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='title',
            new_name='story_title',
        ),
    ]
