# Generated by Django 5.1.7 on 2025-03-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_rename_title_story_story_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story_title',
            new_name='title',
        ),
    ]
