# Generated by Django 5.1.7 on 2025-03-20 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    if not User.objects.exists():
        User.objects.create(
            email='default@example.com',
            author_name='default',
            name='Default',
            surname='User',
            password='unused',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_rename_story_title_story_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_default_user, migrations.RunPython.noop),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stories',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
