# Generated by Django 5.1.7 on 2025-04-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='author_name',
        ),
    ]
