# Generated by Django 5.1.7 on 2025-03-11 12:17

from django.db import migrations, models

def add_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    categories = [
        "fantasy", "scienceFiction", "mysteryThriller", "romance", "horror",
        "historicalFiction", "adventure", "biography", "memoir", "selfHelp",
        "travel", "trueCrime", "scienceTechnology", "history", "politics",
        "business", "sports", "entertainment", "health", "opinionEssays",
        "socialIssues", "inspirational", "fanFiction", "childrenStories", "youngAdult"
    ]

    for category in categories:
        Category.objects.get_or_create(name=category)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
