# Generated by Django 5.1.7 on 2025-03-11 08:30

from django.db import migrations

def add_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    categories = [
        "fantasy", "scienceFiction", "mysteryThriller", "romance", "horror",
        "historicalFiction", "adventure", "biography", "memoir", "selfHelp",
        "travel", "trueCrime", "scienceTechnology", "history", "politics",
        "business", "sports", "entertainment", "health", "opinionEssays",
        "socialIssues", "inspirational", "fanFiction", "childrenStories", "youngAdult"
    ]

    for category in categories:
        Category.objects.get_or_create(name=category)

class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_categories)
    ]
