# Generated by Django 6.0.5 on 2026-06-04 07:23

import writings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0002_remove_writing_author_name_writing_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=writings.models.writing_image_upload_to),
        ),
        migrations.AddField(
            model_name='writing',
            name='image_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
